services:
  - type: web
    name: toxicity-detector
    env: python
    buildCommand: pip install -e .
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: POETRY_VERSION
        value: 2.1.3
